<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.20" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.10" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HIS.Application\HIS.Application.csproj" />
        <ProjectReference Include="..\HIS.Infrastructure\HIS.Infrastructure.csproj" />
        <ProjectReference Include="..\HIS.Presentation.Fhir\HIS.Presentation.Fhir.csproj" />
        <ProjectReference Include="..\HIS.Presentation.HTTP\HIS.Presentation.HTTP.csproj" />
        
    </ItemGroup>

</Project>
