<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.20" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.10" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Reception.Application\Reception.Application.csproj" />
      <ProjectReference Include="..\Reception.Infrastructure\Reception.Infrastructure.csproj" />
      <ProjectReference Include="..\Reception.Presentation.Http\Reception.Presentation.Http.csproj" />
    </ItemGroup>

</Project>
